---
- name: restart_services
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
    - ssh
    - nginx
    - apache2  # Add any services you want to restart after upgrades
  when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "RedHat"
